### ISSUE TITLE
Dosen't work with Node.js 0.12.x

### ISSUE THREAD

**Issue by LinusU** [paulserraino/osx-notify#1]
Hi @paulserraino,

It seems like your library isn't working on the latest node. This is the output I get when trying to require it. I'm looking for a solution as well as I think it's the same problem as LinusU/node-capture-window#1.

``` text
Error: dlopen(/private/tmp/osx-notify/build/Release/addon.node, 1): Symbol not found: _OBJC_CLASS_$_NSAutoreleasePool
  Referenced from: /private/tmp/osx-notify/build/Release/addon.node
  Expected in: dynamic lookup

    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/private/tmp/osx-notify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/private/tmp/osx-notify/index.js:1:97)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by paulserraino** [comment]
oh that's interesting, looks like obj-c is not compiling correctly, but i'm not sure. :crying_cat_face: 

One possible solution would be to specify the version of node you would like to target in `package.json`

``` js
"engines": {
  "node": "0.10.x"
}
```
